// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stroom.Server.Contexts;

#nullable disable

namespace Stroom.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220902033108_hotfix7")]
    partial class hotfix7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Stroom.Shared.Models.CommentDto", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentID"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int?>("TaskID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime");

                    b.Property<int?>("UserID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("CommentID")
                        .HasName("Comment_PK");

                    b.HasIndex("TaskID");

                    b.HasIndex("UserID");

                    b.ToTable("Comment", (string)null);

                    b.HasData(
                        new
                        {
                            CommentID = 1,
                            Comment = "Task is complicated...",
                            TaskID = 1,
                            TimeStamp = new DateTime(2022, 9, 3, 5, 31, 7, 886, DateTimeKind.Local).AddTicks(734),
                            UserID = 1
                        });
                });

            modelBuilder.Entity("Stroom.Shared.Models.ProjectDto", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ProjectID")
                        .HasName("Project_PK");

                    b.HasIndex("UserID");

                    b.ToTable("Project", (string)null);

                    b.HasData(
                        new
                        {
                            ProjectID = 1,
                            Description = "Moon landing program",
                            Name = "Moon colony"
                        });
                });

            modelBuilder.Entity("Stroom.Shared.Models.TaskDto", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskID"), 1L, 1);

                    b.Property<int>("AssigneeID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<float?>("EstimatedTime")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmitionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TaskID")
                        .HasName("Task_PK");

                    b.HasIndex("AssigneeID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Task", (string)null);

                    b.HasData(
                        new
                        {
                            TaskID = 1,
                            AssigneeID = 1,
                            Description = "Name speaks itself",
                            DueDate = new DateTime(2022, 9, 9, 5, 31, 7, 886, DateTimeKind.Local).AddTicks(726),
                            EstimatedTime = 13f,
                            Name = "Change start button color",
                            Priority = 0,
                            ProjectID = 1,
                            Status = 0,
                            SubmitionDate = new DateTime(2022, 9, 2, 5, 31, 7, 886, DateTimeKind.Local).AddTicks(687)
                        });
                });

            modelBuilder.Entity("Stroom.Shared.Models.TimeEntry", b =>
                {
                    b.Property<int>("TimeEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeEntryID"), 1L, 1);

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<float>("Hours")
                        .HasColumnType("real");

                    b.Property<int?>("TaskID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("TimeEntryID")
                        .HasName("TimeEntry_PK");

                    b.HasIndex("TaskID");

                    b.HasIndex("UserID");

                    b.ToTable("TimeEntry", (string)null);

                    b.HasData(
                        new
                        {
                            TimeEntryID = 1,
                            Date = new DateTime(2022, 8, 31, 5, 31, 7, 886, DateTimeKind.Local).AddTicks(729),
                            Hours = 3f,
                            TaskID = 1,
                            UserID = 1
                        });
                });

            modelBuilder.Entity("Stroom.Shared.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "gl.pvn12@gmail.com",
                            Name = "Hlib",
                            Role = 0,
                            Surname = "Pivniev"
                        });
                });

            modelBuilder.Entity("Stroom.Shared.Models.CommentDto", b =>
                {
                    b.HasOne("Stroom.Shared.Models.TaskDto", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Stroom.Shared.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stroom.Shared.Models.ProjectDto", b =>
                {
                    b.HasOne("Stroom.Shared.Models.User", null)
                        .WithMany("Projects")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("Stroom.Shared.Models.TaskDto", b =>
                {
                    b.HasOne("Stroom.Shared.Models.User", "Assignee")
                        .WithMany("Tasks")
                        .HasForeignKey("AssigneeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stroom.Shared.Models.ProjectDto", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Stroom.Shared.Models.TimeEntry", b =>
                {
                    b.HasOne("Stroom.Shared.Models.TaskDto", "Task")
                        .WithMany("TimeEntries")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Stroom.Shared.Models.User", "User")
                        .WithMany("TimeEntries")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stroom.Shared.Models.TaskDto", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("Stroom.Shared.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Projects");

                    b.Navigation("Tasks");

                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
